version: "2"
services:
  webapp:
    image: node
    container_name: isthisanmlm
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./app:/src
    command: bash -c "echo $GOOGLE_ID && cd src && rm -rf node_modules && rm -f package-lock.json && npm install --quiet && npm run build && npm start"
    environment:
      - GOOGLE_ID=${GOOGLE_ID}
