version: "3"
services:
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./suggestions:/suggestions
  webapp:
    build:
      context: ./frontend
      args:
        - BACKEND_BASE_URL=${BACKEND_BASE_URL-https://isthisanmlm.com:8001}
        - GOOGLE_ID=${GOOGLE_ID}
    restart: always
    ports:
      - "80:3000"
