version: "3"
services:
  webapp:
    image: node
    container_name: isthisanmlm
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./app:/src
    command: bash -c "cd src && rm -rf node_modules && rm -f package-lock.json && npm install --quiet && npm run build && npm start"
