version: "3"
services:
  backend:
    build:
      context: ./backend
    restart: always
    volumes:
      - ./suggestions:/suggestions
  webapp:
    build:
      context: ./frontend
      args:
        - GOOGLE_ID=${GOOGLE_ID}
        - FEEDBACK_URL=${FEEDBACK_URL}
        - DONATION_URL=${DONATION_URL}
    restart: always
  proxy:
    image: pottava/proxy
    ports:
        - 80:80
    links:
        - webapp
        - backend
    environment:
        - PROXY_PATTERNS="/api/*=http://backend:8001/,*=http://webapp:3000/"
